name: "Build firmware"

# Run this job on all pushes to master, for pull requests
# as well as tags with a semantic version
on:
  push:
    branches:
      # This avoids having duplicate builds in non-forked PRs
      - "master"
    tags:
      # normal versions
      - "v[0-9]+.[0-9]+.[0-9]+"
      # pre-releases
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request: {}

# Cancel previous PR/branch runs when a new commit is pushed
concurrency:
  group: 'build-firmware-${{ github.ref }}'
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: esp32s3
        path: '.'
        command: |
          idf.py build \
          && cd build \
          && esptool.py \
            --chip esp32s3 merge_bin \
            -o usb2uart_factory.bin \
            --flash_mode dio \
            --flash_size 2MB \
            0x0 bootloader/bootloader.bin \
            0x10000 usb2uart.bin \
            0x8000 partition_table/partition-table.bin